<div class="alert alert-block alert-info">
Singapore Management University<br>
CS105 Statistical Thinking for Data Science
</div>

## Lab 1: Python for Data Science (Exercises)

In [1]:
import numpy as np
import pandas as pd

### Q1: Weighted Average

Write a function `weighted_ave` which takes in two NumPy arrays `values` and `weights`, and returns the weighted average. <br> 

>Example: <br>
>
>*values* = $[21, 55, 80]$ <br>
>*weights* = $[10, 20, 70]$ <br>
>*weighted average* = $\frac{21 \times 10 + 55 \times 20 + 80 \times 70}{10+20+70} = 69.1$

_Hint: consider using the ``numpy.dot()`` function._

In [4]:
def weighted_average(weights, values):
    weighted_ave = 0
    # complete your function
    numerator = 0
    denominator = 0
    for i in range(values.size):
        numerator = numerator + values[i] * weights[i]
        denominator = denominator + weights[i]
    weighted_ave = numerator / denominator
    
    return weighted_ave


#
values = np.array([21, 55, 80])
weights = np.array([10, 20, 70])
weighted_average(weights, values)

69.1

### Q2: Scaling

Write a function taking a NumPy array *values* as its parameter, and scales them to $[0,1]$. <br>Concretely, for each value $x_i$, transform it to $\frac{x_i - min}{max - min}$, where $max$, $min$ are respectively the maximum and minimum values of the array.

_Hint: algebraic manipulations of NumPy arrays can be easily done at the array-level, applying to all elements as the following example demonstrates._

In [7]:
# you do not need to import numpy again if you have run the code of Q7
a = np.arange(5)
print(a)
a = a + 10   # this will add 10 to every element of the array
print(a)

[0 1 2 3 4]
[10 11 12 13 14]


In [17]:
def scaling(values):
    # complete your function
    values.sort()
    values = values - 9
    pass

values = np.array([2,7,5])
print(values)
scaling(values)
print(values)

[2 7 5]
[2 5 7]


### Q3: Average Excluding Max/Min

Write a function `average` that calculates the average score excluding the max and min. <br>
Specifically your function takes in a DataFrame with two columns - judge and score. Return the average score, ignoring the highest score and the lowest score given by the judges

In [ ]:
import pandas as pd

def average(data):
    # complete your function
    
    pass

judges = ["jusge_A", "judge_B", "judge_C", "judge_D", "judge_E", "judge_F"]
scores = [9.0, 4.0, 8.0, 9.8, 10.0, 7.8]
data = pd.DataFrame({"judge":judges, "score":scores})

average(data)

### Q4: Binning

Given a DataFrame with columns - name, length and width, you need to bin the data by their width and calculate the average length for each bin. For the purpose of binning, you only need to make sure the bins take integral values i.e. a width value in [2,3) is classified to have width 2, and likewise a width value in [4,5) is classified to have width 4   

In [ ]:
def bin_average(data):
    # complete your function

    pass


names = ["a", "a", "b", "b", "c", "c"]
lengths = [5.2, 4.3, 3.2, 4.6, 3.2, 5.7]
widths = [1.2, 1.3, 2.2, 2.6, 2.2, 1.7]    
data = pd.DataFrame({"name":names, "length":lengths, "width":widths})

bin_average(data)


### Q5: Grade Column

Given a DataFrame with columns - student and score, write a function `get_grade` that returns a new DataFrame with an additional column called *grade*. *Grade* is computed based on *score*: specifically score >= 70 is an 'A', score >= 60 but lower than 70 is a "B", score >= 50 but lower than 60 is a "C" and score lower than 50 is a "F".

In [ ]:
def get_grade(data):
    # complete your function

    pass  



students = ["Alice", "Bob", "Charlie", "Daniel"]
scores = [60, 40, 77, 58]

data = pd.DataFrame({"student":students, "score":scores})

get_grade(data)